name: AndrewMacLeod
favicon: null
layout_spectrum: 0.9786342580337077
typography_spectrum: 0.43167642992921174
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.19965565903112292
  lightness: 0.2516565527766943
  saturation: 0.4186410631518811
  rhythmicContrast: 0.8813916109502316
purpose: []
